spring.application.name=fraud-detection
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_db
spring.datasource.username=priyanshichauhan
spring.datasource.password=ankit2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true